export const contextSchema = {
  type: 'object',
  properties: {
    domain: { type: 'string' },
    action: { type: 'string' },
    version: { type: 'string' },
    bap_id: { type: 'string' },
    bap_uri: { type: 'string' },
    bpp_id: { type: 'string' },
    bpp_uri: { type: 'string' },
    transaction_id: { type: 'string' },
    message_id: { type: 'string' },
    timestamp: { type: 'string' },
    ttl: { type: 'string' },
  },
  required: [
    'domain',
    'action',
    'version',
    'bap_id',
    'bap_uri',
    'bpp_id',
    'bpp_uri',
    'transaction_id',
    'message_id',
    'timestamp',
    'ttl',
  ],
};
export const searchContextSchema = {
  type: 'object',
  properties: {
    domain: { type: 'string' },
    action: { type: 'string' },
    version: { type: 'string' },
    bap_id: { type: 'string' },
    bap_uri: { type: 'string' },
    transaction_id: { type: 'string' },
    message_id: { type: 'string' },
    timestamp: { type: 'string' },
    ttl: { type: 'string' },
  },
  required: [
    'domain',
    'action',
    'version',
    'bap_id',
    'bap_uri',
    'transaction_id',
    'message_id',
    'timestamp',
    'ttl',
  ],
};
